=== ministryofjustice/laa-criminal-legal-aid-schemas/schemas/0.1/application.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "ministryofjustice/laa-criminal-legal-aid-schemas/main/schemas/0.1/application.json",
  "title": "An application for criminal legal aid",
  "description": "Attributes of a criminal legal aid application",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "schema_version": { "type": "number" },
    "application_type": { "type": "string" },
    "reference": { "type": "number" },
    "created_at": { "type": "string", "format": "date-time" },
    "submitted_at": { "type": "string", "format": "date-time" },
    "date_stamp": { "type": "string", "format": "date-time" },
    "status": { "type": "string" },
    "client_details": { "$ref": "#/definitions/client_details" }
  },
  "required": ["id", "schema_version", "reference", "created_at", "submitted_at", "date_stamp", "status", "client_details"],
  "definitions": {
    "client_details": { "$ref": "client_details.json" }
  }
}

=== ministryofjustice/laa-criminal-legal-aid-schemas/spec/fixtures/applications/application_v0.1.json
{
  "id": "696dd4fd-b619-4637-ab42-a5f4565bcf4a",
  "schema_version": 0.1,
  "application_type": "initial_application",
  "reference": 6000001,
  "created_at": "2022-10-24T08:33:04.000+00:00",
  "submitted_at": "2022-10-24T09:50:04.000+00:00",
  "date_stamp": "2022-10-24T09:50:04.000+00:00",
  "status": "submitted",
  "client_details": {
    "applicant": {
      "first_name": "Kit",
      "last_name": "Pound",
      "nino": "AJ123456C",
      "date_of_birth": "2011-06-09",
      "telephone_number": "07771231231",
      "correspondence_address_type": "other_address",
      "address": {
        "address_line_one": "1 Road",
        "address_line_two": "Village",
        "city": "Some nice city",
        "country": "United Kingdom",
        "postcode": "SW1A 2AA"
      },
      "correspondence_address": {
        "address_line_one": "Correspondence Cottage",
        "address_line_two": "Correspondence Lane",
        "city": "Correspondence City",
        "country": "United Kingdom",
        "postcode": "WM1 1CB"
      }
    }
  }
}
