=== ministryofjustice/laa-criminal-legal-aid-schemas/schemas/1.0/pruned_application.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "ministryofjustice/laa-criminal-legal-aid-schemas/main/schemas/1.0/pruned_application.json",
  "title": "A pruned application for criminal legal aid",
  "description": "Attributes of a pruned criminal legal aid application",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "parent_id": { "type": ["string", "null"] },
    "schema_version": { "type": "number" },
    "reference": { "type": "integer" },
    "application_type": { "type": "string", "enum": ["initial", "post_submission_evidence", "change_in_financial_circumstances"] },
    "created_at": { "type": "string", "format": "date-time" },
    "submitted_at": { "type": "string", "format": "date-time" },
    "date_stamp": { "type": "string", "format": "date-time" },
    "returned_at": { "type": "string", "format": "date-time" },
    "status": { "type": "string", "enum": ["submitted", "returned", "superseded"] },
    "client_details": {
      "type": "object",
      "properties": {
        "applicant": {
          "type": "object",
          "properties": {
            "first_name": { "type": "string" },
            "last_name": { "type": "string" }
          },
          "required": ["first_name", "last_name"],
          "additionalProperties": false
        }
      },
      "required": ["applicant"],
      "additionalProperties": false
    }
  },
  "required": [
    "id", "parent_id", "schema_version", "reference", "application_type",
    "created_at", "submitted_at", "date_stamp", "status", "client_details"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-criminal-legal-aid-schemas/spec/fixtures/application/1.0/pruned_application.json
{
  "id": "243487dc-4727-44eb-9c9c-29809c0eb080",
  "parent_id": null,
  "schema_version": 1.0,
  "reference": 6000118,
  "application_type": "initial",
  "created_at": "2023-05-17T08:01:02.490Z",
  "submitted_at": "2023-06-01T10:36:35.650Z",
  "date_stamp": "2023-06-01T10:36:35.650Z",
  "returned_at": "2023-06-02T11:45:28.126Z",
  "status": "returned",
  "client_details": {
    "applicant": {
      "first_name": "John",
      "last_name": "Doe"
    }
  }
}
